### ISSUE TITLE
peer-to-peer reviews

### ISSUE THREAD

**Issue by nstrvs** [karam084/mobile-version#11]
- [x] Improve animations 
- [x] Fix contact form in mobile view

**Comment by HectorTorresE** [comment]
Overall nice portfolio, Only found a few problem in the project section there seems to be some animation causing visual bugs

**Comment by Kakalanp** [comment]
Your project looks fantastic! 🎉
🔍  There's, of course, some visual bugs mentioned above my review, and one more I'd like to add: 

![image](https://user-images.githubusercontent.com/78335447/150994657-dc01267b-d3b4-4270-af79-bd14fb98507c.png)

The buttons in your navbar doesn't work, try replacing your `li` items for an `a` with an `href="#"` of their corresponding ID's, alternatively, you can add the `a href="#"` inside your `li` 👍 

Good luck! And happy coding. 🍀
